name: shlex
description: Dart module for quoting and parsing shell commands.
version: 2.0.2
homepage: https://github.com/nicomt/dart-shlex

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
